apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nimbus-kubearmor.fullname" . }}
  labels:
    {{- include "nimbus-kubearmor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nimbus-kubearmor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nimbus-kubearmor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
