apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "nimbus.labels" . | nindent 4 }}
  name: leader-election-role
  namespace: nimbus
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nimbus.serviceAccountName" . }}
  labels:
    {{- include "nimbus.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - securityintentbindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - securityintentbindings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - securityintents
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - securityintents/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - nimbuspolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - nimbuspolicies/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
      {{- include "nimbus.labels" . | nindent 4 }}
  name: leader-election-rolebinding
  namespace: nimbus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nimbus.serviceAccountName" . }}
    namespace: nimbus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
      {{- include "nimbus.labels" . | nindent 4 }}
  name: {{ include "nimbus.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nimbus.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nimbus.serviceAccountName" . }}
    namespace: nimbus
